version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.9.0
    steps:
      - checkout
      - run:
          name: npm-install
          command: npm install
      - run:
          name: compile
          command: npm run compile
      #- run:
      #    name: build-for-win
      #    command: npm run build:win
      #- run:
      #    name: create-zip
      #    command: zip -r artifacts/queeg-win32-x64.zip dist/app-win32-x64
      - run:
          name: build-for-linux
          command: npm run build:linux
      - run:
          name: create-zip
          command: zip -r artifacts/queeg-linux-x64.zip dist/app-linux-x64

  publish-github-release:
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=v0.2.0
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/

workflows:
  version: 2
  build-publish:
    jobs:
      - build
      - publish-github-release:
        requires:
            - build